[package]
name = "protobuf"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false
edition = "2018"

[dependencies]
bytes = { version = "0.5", default-features = false }
prost = { path = ".." }
prost-types = { path = "../prost-types" }

[build-dependencies]
anyhow = "1"
# curl 0.4.34 requires Rust 1.40 or higher:
# https://github.com/alexcrichton/curl-rust/pull/356/files#r498918694
curl = "0.4, < 0.4.34"
flate2 = "1.0"
prost-build = { path = "../prost-build" }
tar = "0.4"
tempfile = "3"

[dev-dependencies]
criterion = "0.3"
cfg-if = "0.1"

[lib]
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[[bench]]
name = "dataset"
harness = false
